[changelog]
header = "What's Changed"

body = """
{% for group, commits in commits | group_by(attribute="group") %}

## {{ group }}

{% if group == "📦 Dependencies" %}
{% for commit in commits | unique(attribute="scope") %}
- {{ commit.message | upper_first }} ({{ commit.id | truncate(length=7, end="") }})
{% endfor %}
{% else %}
{% for commit in commits %}
- {{ commit.message | upper_first }} ({{ commit.id | truncate(length=7, end="") }})
{% endfor %}
{% endif %}
{% endfor %}
"""

trim = true

[git]
conventional_commits = true
filter_unconventional = false
sort_commits = "newest"

commit_parsers = [
    { message = "^Update dependency (.+?) to v.+$", group = "📦 Dependencies", scope = "${1}" },
    { message = "^Update (.+?) to v.+$", group = "📦 Dependencies", scope = "${1}" },
    { message = "^Update (.+?) digest to .+$", group = "📦 Dependencies", scope = "${1}" },
    { message = "^Lock file maintenance$", group = "📦 Dependencies", scope = "lock-file-maintenance" },

    { message = "^feat", group = "✨ Features" },
    { message = "^fix", group = "🐛 Bug Fixes" },
    { message = "^perf", group = "⚡ Performance" },
    { message = "^refactor", group = "♻️ Refactoring" },
    { message = "^docs", group = "📚 Documentation" },
    { message = "^test", group = "🧪 Tests" },
    { message = "^ci", group = "🚀 CI/CD" },
    { message = "^build", group = "🔨 Build System" },
    { message = "^chore", group = "🧹 Maintenance" },

    { message = ".*", group = "🔹 Other Changes" }
]

tag_pattern = "v.*"