[changelog]
header = "What's Changed"

body = """
{% for group, commits in commits | group_by(attribute="group") %}

## {{ group }}

{% for commit in commits | unique(attribute="scope") %}
- {{ commit.message | upper_first }} ({{ commit.id | truncate(length=7, end="") }})
{% endfor %}
{% endfor %}
"""

trim = true

[git]
conventional_commits = true
filter_unconventional = false
sort_commits = "newest"

processing_order = [
    "commit_preprocessors",
    "commit_parsers",
    "split_commits",
    "conventional_commits",
    "link_parsers",
]

commit_parsers = [
    { message = "^(?:chore\\(deps\\)|deps): Update dependency (.+?) to v.+$", group = "📦 Dependencies", scope = "${1}" },
    { message = "^(?:chore\\(deps\\)|deps): Update (.+?) to v.+$", group = "📦 Dependencies", scope = "${1}" },
    { message = "^(?:chore\\(deps\\)|deps): Update (.+?) digest to .+$", group = "📦 Dependencies", scope = "${1}" },
    { message = "^(?:chore\\(deps\\)|deps): Lock file maintenance$", group = "📦 Dependencies", scope = "lock-file-maintenance" },

    { message = "^feat", group = "✨ Features" },
    { message = "^fix", group = "🐛 Bug Fixes" },
    { message = "^perf", group = "⚡ Performance" },
    { message = "^refactor", group = "♻️ Refactoring" },
    { message = "^docs", group = "📚 Documentation" },
    { message = "^test", group = "🧪 Tests" },
    { message = "^ci", group = "🚀 CI/CD" },
    { message = "^build", group = "🔨 Build System" },
    { message = "^chore", group = "🧹 Maintenance" },
    
    { message = ".*", group = "🔹 Other Changes" }
]

tag_pattern = "v.*"