[changelog]
header = "What's Changed"

body = """
{% for group, commits in commits | group_by(attribute="group") %}

## {{ group }}

{% for commit in commits %}
- {{ commit.message | upper_first }} ({{ commit.id | truncate(length=7, end="") }})
{% endfor %}
{% endfor %}
"""

trim = true

[git]
conventional_commits = true
filter_unconventional = false
sort_commits = "newest"

commit_parsers = [
    { message = "^feat:", group = "<!-- 00 -->✨ Features" },
    { message = "^fix:", group = "<!-- 01 -->🐛 Bug Fixes" },
    { message = "^perf:", group = "<!-- 02 -->⚡ Performance" },
    { message = "^refactor:", group = "<!-- 03 -->♻️ Refactoring" },
    { message = "^revert:", group = "<!-- 04 -->⏪ Reverts" },
    { message = "^ci:", group = "<!-- 05 -->🚀 CI/CD" },
    { message = "^build:", group = "<!-- 06 -->🔨 Build System" },
    { message = "^docs:", group = "<!-- 07 -->📚 Documentation" },
    { message = "^test:", group = "<!-- 08 -->🧪 Tests" },
    { message = "^chore:", group = "<!-- 09 -->🧹 Maintenance" },
    { message = "^deps:", group = "<!-- 10 -->📦 Dependencies" },
    { message = ".*", group = "<!-- 11 -->🔹 Other Changes" }
]

tag_pattern = "v.*"