services:
  app:
    image: git.darkzoul.org/dark_zoul/campersite:latest
    container_name: campersite_app
    environment:
      - DB_PATH=/app/data/app.db
      - NODE_ENV=production
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_PORT=3001
      - SESSION_SECRET=${SESSION_SECRET}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    volumes:
      - ./data:/app/data
      - ./public/images:/app/public/images
    restart: unless-stopped
    networks:
      - traefik-proxy
    labels:
      # traefik
      traefik.enable: "true"
      # Main router
      traefik.http.routers.app.rule: "Host(`recomte.ru`)"
      traefik.http.routers.app.entrypoints: "websecure"
      traefik.http.routers.app.tls.certresolver: "letsencrypt"
      traefik.http.routers.app.middlewares: "nginx-headers@docker"
      traefik.http.routers.app.service: "app"
      # WWW redirect router
      traefik.http.routers.app-www.rule: "Host(`www.recomte.ru`)"
      traefik.http.routers.app-www.entrypoints: "websecure"
      traefik.http.routers.app-www.tls.certresolver: "letsencrypt"
      traefik.http.routers.app-www.middlewares: "redirect-www-to-root,nginx-headers@docker"
      traefik.http.routers.app-www.service: "app"
      # Redirect middleware
      traefik.http.middlewares.redirect-www-to-root.redirectregex.regex: "^https://www\\.recomte\\.ru/(.*)"
      traefik.http.middlewares.redirect-www-to-root.redirectregex.replacement: "https://recomte.ru/$${1}"
      traefik.http.middlewares.redirect-www-to-root.redirectregex.permanent: "true"
      # Service
      traefik.http.services.app.loadbalancer.server.port: "3000"
      traefik.http.routers.admin.rule: "Host(`admin.recomte.ru`)"
      traefik.http.routers.admin.entrypoints: "websecure"
      traefik.http.routers.admin.tls.certresolver: "letsencrypt"
      traefik.http.routers.admin.middlewares: "nginx-headers@docker"
      traefik.http.routers.admin.service: "app-admin"
      traefik.http.services.app-admin.loadbalancer.server.port: "3001"
      # Headers
      traefik.http.middlewares.nginx-headers.headers.customResponseHeaders.Server: ""

  app_test:
    image: git.darkzoul.org/dark_zoul/campersite:dev
    container_name: campersite_app_test
    environment:
      - DB_PATH=/app/data/app.db
      - NODE_ENV=production
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_PORT=3001
      - SESSION_SECRET=${SESSION_SECRET}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    volumes:
      - ./data:/app/data
      - ./public/images:/app/public/images
    restart: unless-stopped
    networks:
      - traefik-proxy
    labels:
      # traefik
      traefik.enable: "true"
      # Main router 
      traefik.http.routers.app-test.rule: "Host(`test.recomte.ru`)"
      traefik.http.routers.app-test.entrypoints: "websecure"
      traefik.http.routers.app-test.tls.certresolver: "letsencrypt"
      traefik.http.routers.app-test.middlewares: "nginx-headers@docker"
      traefik.http.routers.app-test.service: "app-test"
      # Service
      traefik.http.services.app-test.loadbalancer.server.port: "3000"
      traefik.http.routers.app-test-admin.rule: "Host(`admin.test.recomte.ru`)"
      traefik.http.routers.app-test-admin.entrypoints: "websecure"
      traefik.http.routers.app-test-admin.tls.certresolver: "letsencrypt"
      traefik.http.routers.app-test-admin.middlewares: "nginx-headers@docker"
      traefik.http.routers.app-test-admin.service: "app-test-admin"
      traefik.http.services.app-test-admin.loadbalancer.server.port: "3001"
    
networks:
  traefik-proxy:
    external: true    
      
