minimumReleaseAge: 1440
packages:
  - .

onlyBuiltDependencies:
  - '@parcel/watcher'
  - argon2
  - better-sqlite3
  - sharp

allowBuilds:
  '@parcel/watcher': true
  argon2: true
  better-sqlite3: false
  sharp: true
