services:
  app:
    image: git.darkzoul.org/dark_zoul/recomte:latest
    container_name: recomte_app
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      # Admin credentials
      - ADMIN_USERNAME=${ADMIN_USERNAME} # MUST be set for admin interface to work
      - ADMIN_PASSWORD=${ADMIN_PASSWORD} # MUST be set for admin interface to work
      # Session secret
      - SESSION_SECRET=${SESSION_SECRET} # MUST be set for app to work
      - SITE_URL=https://recomte.ru
      - ADMIN_URL=https://admin.recomte.ru

      # Optional --------------------------------------------
      - DB_PATH=/app/data/app.db
      - PORT=${PORT:-3000}
      - ADMIN_PORT=${ADMIN_PORT:-3001}
      #Logging - global level or separate for admin and public
      #- LOG_LEVEL=${LOG_LEVEL:-info}
      - ADMIN_LOG_LEVEL=${ADMIN_LOG_LEVEL:-info}
      - PUBLIC_LOG_LEVEL=${PUBLIC_LOG_LEVEL:-info}

    volumes:
      - ../storage/prod/db:/app/data
      - ../storage/prod/backups:/app/data/backups
      - ../storage/prod/images/caravans:/app/public/images/caravans
    restart: unless-stopped
    networks:
      - traefik-proxy
    labels:
      # traefik
      traefik.enable: "true"
      traefik.docker.network: "traefik-proxy"
      # Main router
      traefik.http.routers.app.rule: "Host(`recomte.ru`)"
      traefik.http.routers.app.entrypoints: "websecure"
      traefik.http.routers.app.tls.certresolver: "letsencrypt"
      traefik.http.routers.app.middlewares: "nginx-headers@docker"
      traefik.http.routers.app.service: "app"
      # WWW redirect router
      traefik.http.routers.app-www.rule: "Host(`www.recomte.ru`)"
      traefik.http.routers.app-www.entrypoints: "websecure"
      traefik.http.routers.app-www.tls.certresolver: "letsencrypt"
      traefik.http.routers.app-www.middlewares: "redirect-www-to-root,nginx-headers@docker"
      traefik.http.routers.app-www.service: "app"
      # Redirect middleware
      traefik.http.middlewares.redirect-www-to-root.redirectregex.regex: "^https://www\\.recomte\\.ru/(.*)"
      traefik.http.middlewares.redirect-www-to-root.redirectregex.replacement: "https://recomte.ru/$${1}"
      traefik.http.middlewares.redirect-www-to-root.redirectregex.permanent: "true"
      # Service
      traefik.http.services.app.loadbalancer.server.port: "3000"
      traefik.http.routers.admin.rule: "Host(`admin.recomte.ru`)"
      traefik.http.routers.admin.entrypoints: "websecure"
      traefik.http.routers.admin.tls.certresolver: "letsencrypt"
      traefik.http.routers.admin.middlewares: "nginx-headers@docker"
      traefik.http.routers.admin.service: "app-admin"
      traefik.http.services.app-admin.loadbalancer.server.port: "3001"
      # Headers
      traefik.http.middlewares.nginx-headers.headers.customResponseHeaders.Server: ""

  app_test:
    image: git.darkzoul.org/dark_zoul/recomte:dev
    container_name: recomte_app_test
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      # Admin credentials
      - ADMIN_USERNAME=${ADMIN_USERNAME} # MUST be set for admin interface to work
      - ADMIN_PASSWORD=${ADMIN_PASSWORD} # MUST be set for admin interface to work
      # Session secret
      - SESSION_SECRET=${SESSION_SECRET} # MUST be set for app to work
      - SITE_URL=https://test.recomte.ru
      - ADMIN_URL=https://admin.test.recomte.ru

      # Optional --------------------------------------------
      - DB_PATH=/app/data/app.db
      - PORT=${PORT:-3000}
      - ADMIN_PORT=${ADMIN_PORT:-3001}
      #Logging - global level or separate for admin and public
      #- LOG_LEVEL=${LOG_LEVEL:-info}
      - ADMIN_LOG_LEVEL=${ADMIN_LOG_LEVEL:-info}
      - PUBLIC_LOG_LEVEL=${PUBLIC_LOG_LEVEL:-info}

    volumes:
      - ../storage/test/db:/app/data
      - ../storage/test/backups:/app/data/backups
      - ../storage/test/images/caravans:/app/public/images/caravans
    restart: unless-stopped
    networks:
      - traefik-proxy
    labels:
      # traefik
      traefik.enable: "true"
      traefik.docker.network: "traefik-proxy"
      # Main router 
      traefik.http.routers.app-test.rule: "Host(`test.recomte.ru`)"
      traefik.http.routers.app-test.entrypoints: "websecure"
      traefik.http.routers.app-test.tls.certresolver: "letsencrypt"
      traefik.http.routers.app-test.middlewares: "nginx-headers@docker"
      traefik.http.routers.app-test.service: "app-test"
      # Service
      traefik.http.services.app-test.loadbalancer.server.port: "3000"
      traefik.http.routers.app-test-admin.rule: "Host(`admin.test.recomte.ru`)"
      traefik.http.routers.app-test-admin.entrypoints: "websecure"
      traefik.http.routers.app-test-admin.tls.certresolver: "letsencrypt"
      traefik.http.routers.app-test-admin.middlewares: "nginx-headers@docker"
      traefik.http.routers.app-test-admin.service: "app-test-admin"
      traefik.http.services.app-test-admin.loadbalancer.server.port: "3001"
    
networks:
  traefik-proxy:
    external: true    
      
